name: crawl
version: 0.6.0
homepage: https://github.com/creativebracket/crawl
description: A cli for creating pubspec files and managing it's packages.
issue_tracker: https://github.com/creativebracket/crawl/issues
environment: 
  sdk: '>=2.8.1 <3.0.0'
dependencies: 
  args: ^1.6.0
  dcli: ^0.29.2
  http: ^0.12.2
  pubspec: ^0.1.5
dev_dependencies: 
  pedantic: ^1.9.0
  test: ^1.14.4
executables: 
  crawl: 
